### ISSUE TITLE
无法生成可执行文件test

### ISSUE THREAD

**Issue by wenxuan70** [chanchann/wfrest_usage#1]
大佬，我在使用这个仓库的cmake配置文件进行编译时，会出现下面这个错误。

<img width="584" alt="image" src="https://user-images.githubusercontent.com/55948263/236222582-45a4989e-407b-4fbe-90c8-088569da498a.png">

参考stackoverflow上的回答，是test名称跟cmake的功能冲突。

https://stackoverflow.com/questions/46638704/cmake-error-target-name-test-is-reserved-or-not-valid

**Comment by wenxuan70** [comment]
@chanchann 大佬，这块地方是否需要修改下？改成example、demo或者其他单词。
https://github.com/wfrest/wfrest_usage/blob/main/CMakeLists.txt#L48-L49

**Comment by chanchann** [comment]
感谢建议哈

**Comment by chanchann** [comment]
> @chanchann 大佬，这块地方是否需要修改下？改成example、demo或者其他单词。 https://github.com/wfrest/wfrest_usage/blob/main/CMakeLists.txt#L48-L49

已修改
